# Clippy configuration for FluxEncrypt

# The maximum cognitive complexity a function can have
cognitive-complexity-threshold = 30

# The maximum number of lines a function or method can have
too-many-lines-threshold = 100

# The minimum rust version
msrv = "1.89.0"

# Whether to allow mixed uninlined format args, e.g. `format!("{} {}", a, foo.bar)`
allow-mixed-uninlined-format-args = false

# Whether to suppress the restriction lint suggesting to remove a clone() when not necessary

# The maximum number of arguments a function can have
too-many-arguments-threshold = 7

# The maximum number of bounds a generic type can have
type-complexity-threshold = 250

# The maximum size of objects (in bytes) that will be linted. Larger objects are ok on the heap
trivial-copy-size-limit = 128

# The minimum number of enum variants for the type to be considered as having too many variants
enum-variant-size-threshold = 200

# The maximum number of variants in an enum before it's considered too large
large-error-threshold = 25

# Whether to accept a enum variant to be named `Error`
allow-expect-in-tests = true

# Whether to check for `expect` in test functions
allow-unwrap-in-tests = true

# List of disallowed names to lint about
disallowed-names = ["foo", "baz", "quux"]

# Suppress lints whenever the suggested change would cause breakage for other crates
avoid-breaking-exported-api = false