# Rustfmt configuration for FluxEncrypt

# Edition to use for formatting (2015, 2018, or 2021)
edition = "2021"

# Maximum width of each line
max_width = 100

# Ideal width of each line (used for comments and strings)
comment_width = 80

# Hard tab or soft tab
hard_tabs = false

# Number of spaces per tab
tab_spaces = 4

# Maximum width of the args of a function call before falling back to vertical formatting
fn_args_layout = "Tall"

# Maximum width of the args of a struct initializer before falling back to vertical formatting
struct_field_align_threshold = 0

# Where to put a binary operator when a binary expression goes multiline
binop_separator = "Front"

# Remove blank lines at the start or end of a block
remove_nested_parens = true

# Use small heuristics to determine parameter layout
use_small_heuristics = "Default"

# Format strings
format_strings = true

# Format the metavariable matching patterns in macros
format_macro_matchers = true

# Control the layout of imports and extern crate items
imports_layout = "Mixed"

# Merge or split imports/extern crates whose paths are matching
merge_imports = true

# Group imports by module
group_imports = "StdExternalCrate"

# Controls the ordering of imports
reorder_imports = true

# Controls the ordering of extern crate statements
reorder_extern_crates = true

# Reorder impl items
reorder_impl_items = true

# Add trailing commas
trailing_comma = "Vertical"

# If true, the empty line at the beginning of the file is removed
skip_children = false

# Control the case of the letters in hexadecimal literal values
hex_literal_case = "Lower"

# Use verbose comments
verbose_comments = false

# Controls the positioning of leading comments in multiline function calls
normalize_comments = true

# Format doc comments
normalize_doc_attributes = true

# Controls the ordering of module stmts
reorder_modules = true

# Force multiline if any argument has line comment
force_multiline_blocks = false

# Merge multiple derives into one
merge_derives = true

# Use field initializer shorthand if possible
use_field_init_shorthand = false

# Don't format the contents of raw string literals
format_code_in_doc_comments = true

# Wrap multiline match arms in blocks
wrap_matches = true

# Controls the order of match arms
match_arm_blocks = true

# Indent match arms instead of keeping them at the same indentation level as the match keyword
match_arm_leading_pipes = "Never"

# Force single line if-else formatting
force_explicit_abi = true

# Combine control expressions with function calls
combine_control_expr = true

# Require a specific version of rustfmt
required_version = "1.7.0"

# Use try shorthand
use_try_shorthand = false

# Format generated files
format_generated_files = true