# cargo-deny configuration for FluxEncrypt
# https://embarkstudios.github.io/cargo-deny/

[graph]
targets = []
all-features = false
no-default-features = false

[output]
feature-depth = 1

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = []

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "MPL-2.0",
    "Unicode-3.0",
]
confidence-threshold = 0.8
exceptions = [
    { allow = ["OpenSSL"], crate = "ring" },
]

[bans]
multiple-versions = "allow"
wildcards = "allow"
highlight = "all"
allow = []
skip = []
skip-tree = []

[sources]
unknown-registry = "allow"
unknown-git = "allow"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []